vich_uploader:
  db_driver: orm

  mappings:
    images:
        uri_prefix: /images/players-images
        upload_destination: "%kernel.project_dir%/public/images/players-images"
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
